import React from 'react';

const Home = () => {
    return (
        <div>

<div class="d-flex bd-highlight mb-3 nav-home-padding">
  <div class="me-auto p-2 bd-highlight"><h4>Home/Writing Assistant</h4></div>
  <div class="p-2 bd-highlight"><button className='save-filter '>Save </button></div>
  <div class="p-2 bd-highlight"><button className='save-filter'>Filter</button></div>
</div>
<h6>Enter input to get <span className='writing'> Writing Assistant</span></h6>
       <div className="row">
        <div className="col-7">
Word 0/0 Count 0/250
<div className="d-flex">
  <span className='bld'>B</span>
  <span className='ita'>I</span>
  <span className='hyper'>HyperLink</span>
  <span className='hyper'>Text Cut</span>
  <span className='hyper'>Underline</span>
  <span className='hyper'>Underline</span>
 
</div>
<hr className='horizontal'/>
<div className='text-edit'>
<p>As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title <span className='gray-span'>was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.</span> </p>
</div>
        </div>
        <div className="col-5">
<div className="text d-flex">
Copy <div className='horizon'></div><p>As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.</p>

</div>
<div className="text mt-2 d-flex">
Copy <div className='horizon'></div><p>As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.</p>

</div>
<div className="text d-flex">
Copy <div className='horizon'></div><p>As artificial intelligence continues to evolve, it is becoming increasingly capable of generating original and insightful content. This blog post is a prime example; the title was generated by AI within 10 seconds. AI is quickly becoming a powerful tool for content creators and marketers alike.</p>

</div>
        </div>
       </div>
       
        </div>
    );
};

export default Home;